services:
  pr-agent:
    build:
      context: ../
      dockerfile: ci/Dockerfile
      target: bitbucket_server_webhook   # folosește stage-ul webhook
    container_name: pr-agent
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "30014:30014"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
