services:
  pr-agent:
    image: codiumai/pr-agent:bitbucket_app
    build:
      context: ../
      dockerfile: ci/Dockerfile
      target: bitbucket_app   # folosește stage-ul webhook
    container_name: pr-agent
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "30014:3000"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
